# Generated by Django 3.1.7 on 2021-05-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterUniqueTogether(
            name='anime',
            unique_together={('title', 'author')},
        ),
    ]
